title: "Computational Economic Notes"
email: zedtaha@gmail.com
description: "A scientific journal website"
baseurl: "/Computational-Economic-Notes"
url: "https://compeconote.github.io"

theme: minima

markdown: kramdown
plugins:
  - jekyll-feed

# Collections configuration
collections:
  papers:
    output: true
    permalink: /papers/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
