title: "Computational Economic Notes"
email: zedtaha@gmail.com
description: "A scientific journal website"
baseurl: "" 
url: "https://tahazaghdoudi.github.io"  

theme: minima

markdown: kramdown
plugins:
  - jekyll-feed

collections:
  journal:
    output: true
    permalink: /journal/:name
